import pandas as pd
import yaml
from resolvai import logger
from resolvai.config.configuration import ConfigurationManager
from resolvai.utils.llm_client import LLMClient
import time

def auto_label_golden_set():
    cm = ConfigurationManager()
    config = cm.get_golden_set_config()
    
    # Load the template generated by stage 06
    template_df = pd.read_csv(config.golden_template_path)
    
    # Load intent definitions for the LLM
    with open("config/intents.yaml") as f:
        intents = yaml.safe_load(f)
    
    llm_call = LLMClient.get(config.llm_provider, config.llm_model)
    
    rate_limit_warned = False
    
    def generate_checklist(text):
        nonlocal rate_limit_warned
        prompt = f"""You are evaluating customer support messages.
For the following customer message, what are 2-3 essential elements a good support agent reply MUST contain?
Keep it brief. E.g. "- Acknowledge the issue\n- Ask for order number"

Customer message: "{text}"
Checklist:"""
        try:
            time.sleep(0.3)
            return llm_call(prompt, max_tokens=60).strip()
        except Exception as e:
            if not rate_limit_warned:
                logger.warning(f"Checklist API failed (likely Rate Limits). Mocking remaining checklists. First error: {e}")
                rate_limit_warned = True
            return "- Acknowledge the issue\n- Offer assistance"
            
    # Heuristics for auto-labeling
    # We will use the suggested_intent as the ground_truth_intent (silver standard)
    template_df["ground_truth_intent"] = template_df["suggested_intent"]
    
    escalation_reasons = []
    ground_truth_escalate = []
    checklists = []
    
    escalation_config = cm.get_escalation_config()
    risk_keywords = escalation_config.risk_keywords
    
    logger.info("Auto-labeling golden set (silver-standard)... this takes a minute.")
    
    for _, row in template_df.iterrows():
        text = str(row["customer_text"]).lower()
        intent = str(row["suggested_intent"])
        
        # Determine escalation based on risk keywords or specific intent classes
        is_risk = any(k.lower() in text for k in risk_keywords)
        is_escalation_intent = any(w in intent.lower() for w in ["complaint", "billing", "refund", "legal", "scam"])
        
        if is_risk:
            ground_truth_escalate.append(True)
            escalation_reasons.append("risk keywords present")
        elif is_escalation_intent:
            ground_truth_escalate.append(True)
            escalation_reasons.append(f"intent '{intent}' requires escalation")
        else:
            ground_truth_escalate.append(False)
            escalation_reasons.append("routine issue, safe for auto-handle")
            
        checklists.append(generate_checklist(row["customer_text"]))
        
    template_df["ground_truth_escalate"] = ground_truth_escalate
    template_df["escalation_reason"] = escalation_reasons
    template_df["good_reply_checklist"] = checklists
    
    template_df.to_csv(config.golden_set_path, index=False)
    logger.info(f"Auto-labeled {len(template_df)} rows and saved to {config.golden_set_path}")

if __name__ == "__main__":
    auto_label_golden_set()
